nodes = [
  { :hostname => 'webserver1.test', :ip => '10.101.0.2' },
  { :hostname => 'webserver2.test', :ip => '10.101.0.3' }
]

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :virtualbox do |vb|
    vb.memory = 512
    vb.cpus = 1
  end

  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.hostname = node[:hostname]
      nodeconfig.vm.network "private_network", ip: node[:ip]
 
      nodeconfig.vm.provision :ansible do |ansible|
        ansible.playbook = "site.yml"
        ansible.inventory_path = "inventory/development"
      end
    end
  end
end

