galaxy_info:
  author: stanlam1987
  description: basic configuration
  company: "BCIT NASP"

  license: license (GPLv2, CC-BY, etc)

  min_ansible_version: 2.4

  platforms:
  - name: CentOS
    versions:
    - 7

  galaxy_tags:
    - nginx
    - loadbalancer
